config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users

  # в профиле юзера показываем его игры, на главной - список лучших игроков
  resources :users, only: [:index, :show]

  resources :games, only: [:create, :show] do
    # доп. методы ресурса:
    put 'help', on: :member # помощь зала
    put 'answer', on: :member # ответ на текущий вопрос
    put 'take_money', on: :member #  игрок берет деньги
  end

  # Ресурс в единственном числе - ВопросЫ
  # для загрузки админом сразу пачки вопросОВ
  resource :questions, only: [:new, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WWBM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg buffer-bottom">
      <div class="container">
        <%= link_to 'Кто хочет стать миллионером?', root_path,
          class: 'navbar-brand text-white text-decoration-none fw-bold' %>
        <% if user_signed_in? %>
          <div class="navbar-form navbar-right">

            <% if current_user.is_admin? %>
              <%= link_to 'Админка', rails_admin_path,
                class: 'btn navbar-btn btn-danger btn-xs' %>
              <%= link_to 'Залить новые вопросы', new_questions_path,
                class: 'btn navbar-btn btn-warning btn-xs' %>
            <% end %>

            <%= link_to content_tag(:span, "#{current_user.name} - #{number_to_currency current_user.balance}"),
                        user_path(current_user),
                        class: 'btn navbar-btn text-white'
            %>
            <%= link_to 'Новая игра', games_path, data: { turbo_method: :post },
              class: 'btn navbar-btn btn-success btn-xs' %>
            <%= link_to 'Выйти', destroy_user_session_path, data: { turbo_method: :delete },
              class: 'btn btn-info btn-xs navbar-btn' %>
          </div>
        <% else %>
          <div class="navbar-form navbar-right">
            <%= link_to 'Войти', new_user_session_path, class: 'btn btn-primary' %>
            <%= link_to 'Зарегистрироваться', new_user_registration_path,
              class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </nav>

    <% if flash[:notice].present? %>
      <div data-controller="flash" class="alert alert-success alert-dismissible mx-3 fade show"
        data-timeout="3000" role="alert">
        <%= flash[:notice] %>
        <button data-action="flash#dismiss" type="button" class="btn-close"
          data-bs-dismiss="alert" aria-label="Close">
      </div>
    <% elsif flash[:alert].present? %>
      <div data-controller="flash" class="alert alert-danger alert-dismissible mx-3 fade show"
        data-timeout="3000" role="alert">
        <%= flash[:alert] %>
        <button data-action="flash#dismiss" type="button" class="btn-close"
          data-bs-dismiss="alert" aria-label="Close">
      </div>
    <% end %>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div>
    </div>

    <footer class="text-center text-white mt-auto">
      <div class="text-center p-3">
        &copy
        <%= link_to t('app.company'), 'https://goodprogrammer.ru',
          class: 'text-white' %>
        2023
      </div>
    </footer>
  </body>
</html>